name: BuildDeploy ActionBuildNumber App
env:  
  APP_FOLDER_PATH: ActionBuildNumber
  
on:    
  # push:
  #   branches: main
  #   paths:
  #   - 'frontend/**'    
    
  workflow_dispatch:  

jobs:
  Build-Publish-Deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v4    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: update build number from GH Action 
      uses: TomaszKandula/variable-substitution@v1.0.2
      with:
          files: '{{env.APP_FOLDER_PATH}}/appsettings.json'
      env:
          BuildNumber: "GH-Action"          
          
    - name: Restore, Build, Test, Publish  
      run: |
        cd {{env.APP_FOLDER_PATH}}
        dotnet restore   
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp     
        
    - name: Deploy App to Azure WebService
      uses: Azure/webapps-deploy@v3.0.1
      with:               
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}      
        clean: true
        package: ${{env.DOTNET_ROOT}}/myapp        
