name: Close Issue

on: 
  workflow_dispatch:
     inputs:
      TimIssue:
        description: "which issue shall we close?"
        default: "my input value"
  
jobs:
  closeissue:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Close Issue
      uses: peter-evans/close-issue@v3.0.1
      with:
          issue-number: ${{ inputs.Issue }} 
          comment: Auto-closing issue
          close-reason: completed
