name: Action-to-Test

on:
    workflow_dispatch:

jobs:
  dinner:
    name: whats-for-dinner
    runs-on: ubuntu-latest
    steps:
      - name: Tell me what you ate
        run: echo " ${{github.ACTOR}} had ${{ vars.DINNER }} for dinner last night"
  
