name: ShortSHA

on: 
  workflow_dispatch:
env:
  ACR_LOGIN_SERVER: jfvacr.azurecr.io  
  APP_NAME: dncapp
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:              
      - name: Setup vars 
        run: |      
         echo "The SHA is: $GITHUB_SHA"          
         echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c 1-7`" >> $GITHUB_ENV                 
         echo "CONTAINER_TAG='echo ${{ env.ACR_LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}'" >> $GITHUB_ENV           
      - name: Print vars
        # variables cannot be used in the same step where they are created
        run: |         
         echo ${env.SHORT_SHA}
         echo ${env.CONTAINER_TAG}
         echo ${{env.SHORT_SHA}}
         echo ${{env.CONTAINER_TAG}}
         
