name: ShortSHA

on: 
  workflow_dispatch:
env:
  ACR_LOGIN_SERVER: jfvacr.azurecr.io  
  APP_NAME: dncapp
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:              
      - run: |      
            echo "The SHA is: $GITHUB_SHA"  
            #SHORT_SHA=  ${GITHUB_SHA} | cut -c 1-7
            #echo "$SHORT_SHA"
            echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c 1-7`" >> $GITHUB_ENV  
            echo ${SHORT_SHA}
            #echo ${{SHORT_SHA}}
            echo $SHORT_SHA
            echo "this is the last line"
            #echo "CONTAINER_TAG='echo ${{ env.ACR_LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}'" >> $GITHUB_ENV  
